# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(611, 503)
        self.centralwidget = QtWidgets.QWidget(EditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 611, 451))
        self.listWidget.setObjectName("listWidget")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(30, 460, 75, 23))
        self.addButton.setObjectName("addButton")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(140, 460, 75, 23))
        self.updateButton.setObjectName("updateButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(250, 460, 75, 23))
        self.deleteButton.setObjectName("deleteButton")
        EditWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "MainWindow"))
        self.addButton.setText(_translate("EditWindow", "Add"))
        self.updateButton.setText(_translate("EditWindow", "Update"))
        self.deleteButton.setText(_translate("EditWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditWindow = QtWidgets.QMainWindow()
    ui = Ui_EditWindow()
    ui.setupUi(EditWindow)
    EditWindow.show()
    sys.exit(app.exec_())
