# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PythonApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1016, 610)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_page = QtWidgets.QFrame(self.centralwidget)
        self.edit_page.setGeometry(QtCore.QRect(100, 640, 801, 521))
        self.edit_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_page.setObjectName("edit_page")
        self.editButton = QtWidgets.QPushButton(self.edit_page)
        self.editButton.setGeometry(QtCore.QRect(110, 490, 75, 23))
        self.editButton.setObjectName("editButton")
        self.listWidget = QtWidgets.QListWidget(self.edit_page)
        self.listWidget.setGeometry(QtCore.QRect(0, 10, 791, 471))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(17)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget::item {\n"
"     border-style: solid;\n"
"     border-radius:20px; \n"
"        background-color:transparent;\n"
"  }\n"
"  QListWidget::item:selected {\n"
"     background-color: rgba(48, 131, 232, 0.5);\n"
"     border-radius:20px;\n"
"  }\n"
"\n"
"  QListWidget {\n"
"     background-color: transparent;\n"
"     border-radius:20px;\n"
"  }\n"
"\n"
"QScrollBar:vertical {border: none;background-color: #282828;width: 10px;margin: 25px 0 0px 0;border-radius: 4px;}\n"
"QScrollBar::handle:vertical{border-radius: 4px;border-color: rgba(216, 216, 216, 75%);border-width: 1px; border-style: solid; background-color: rgba(216, 216, 216, 75%); min-height: 25px;}\n"
"QScrollBar::add-line:vertical{width: 0px; height: 0px;}\n"
"QScrollBar::sub-line:vertical{width: 0px; height: 0px;}\n"
"QScrollBar::add-page:vertical{background-color: none;border-radius: 4px;}\n"
"QScrollBar::sub-page:vertical{background-color: none;border-radius: 4px;}")
        self.listWidget.setObjectName("listWidget")
        self.addButton = QtWidgets.QPushButton(self.edit_page)
        self.addButton.setGeometry(QtCore.QRect(0, 490, 75, 23))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.edit_page)
        self.deleteButton.setEnabled(True)
        self.deleteButton.setGeometry(QtCore.QRect(220, 490, 75, 23))
        self.deleteButton.setObjectName("deleteButton")
        self.settingsDownButton = QtWidgets.QPushButton(self.edit_page)
        self.settingsDownButton.setGeometry(QtCore.QRect(750, 480, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.settingsDownButton.setFont(font)
        self.settingsDownButton.setStyleSheet("border-radius:20px;")
        self.settingsDownButton.setObjectName("settingsDownButton")
        self.add_page = QtWidgets.QFrame(self.centralwidget)
        self.add_page.setGeometry(QtCore.QRect(100, 600, 801, 561))
        self.add_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_page.setObjectName("add_page")
        self.addlistWidget = QtWidgets.QListWidget(self.add_page)
        self.addlistWidget.setGeometry(QtCore.QRect(390, 100, 391, 421))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.addlistWidget.setFont(font)
        self.addlistWidget.setStyleSheet("QListWidget::item {\n"
"     border-style: solid;\n"
"     border-radius:20px; \n"
"        background-color:transparent;\n"
"  }\n"
"  QListWidget::item:selected {\n"
"     background-color: rgba(48, 131, 232, 0.5);\n"
"     border-radius:20px;\n"
"  }\n"
"\n"
"  QListWidget {\n"
"     background-color: transparent;\n"
"     border-radius:20px;\n"
"  }\n"
"\n"
"QScrollBar:vertical {border: none;background-color: #282828;width: 10px;margin: 25px 0 0px 0;border-radius: 4px;}\n"
"QScrollBar::handle:vertical{border-radius: 3px;border-color: rgba(216, 216, 216, 75%);border-width: 1px; border-style: solid; background-color: rgba(216, 216, 216, 75%); min-height: 25px;}\n"
"QScrollBar::add-line:vertical{width: 0px; height: 0px;}\n"
"QScrollBar::sub-line:vertical{width: 0px; height: 0px;}\n"
"QScrollBar::add-page:vertical{background-color: none;border-radius: 4px;}\n"
"QScrollBar::sub-page:vertical{background-color: none;border-radius: 4px;}")
        self.addlistWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.addlistWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.addlistWidget.setObjectName("addlistWidget")
        self.confirmButton = QtWidgets.QPushButton(self.add_page)
        self.confirmButton.setGeometry(QtCore.QRect(0, 530, 75, 23))
        self.confirmButton.setObjectName("confirmButton")
        self.addDownButton = QtWidgets.QPushButton(self.add_page)
        self.addDownButton.setGeometry(QtCore.QRect(750, 520, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addDownButton.setFont(font)
        self.addDownButton.setStyleSheet("border-radius:20px;")
        self.addDownButton.setObjectName("addDownButton")
        self.label_2 = QtWidgets.QLabel(self.add_page)
        self.label_2.setGeometry(QtCore.QRect(440, 60, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Courgette")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.add_page)
        self.label.setGeometry(QtCore.QRect(70, 240, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Courgette")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name_input = QtWidgets.QTextEdit(self.add_page)
        self.name_input.setGeometry(QtCore.QRect(70, 280, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.name_input.setFont(font)
        self.name_input.setObjectName("name_input")
        self.add_backframe = QtWidgets.QFrame(self.centralwidget)
        self.add_backframe.setGeometry(QtCore.QRect(95, 600, 801, 561))
        self.add_backframe.setStyleSheet("border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(48, 168, 196, 0.7), stop:1 rgba(218, 84, 255, 0.7));")
        self.add_backframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_backframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_backframe.setObjectName("add_backframe")
        self.settings_backframe = QtWidgets.QFrame(self.centralwidget)
        self.settings_backframe.setGeometry(QtCore.QRect(95, 600, 801, 561))
        self.settings_backframe.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(125, 226, 252, 0.8), stop:1 rgba(185, 182, 229, 0.8));\n"
"border-radius:20px;")
        self.settings_backframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_backframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_backframe.setObjectName("settings_backframe")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(130, 200, 771, 131))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.testButton_2 = QtWidgets.QPushButton(self.main_frame)
        self.testButton_2.setGeometry(QtCore.QRect(20, 50, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testButton_2.setFont(font)
        self.testButton_2.setStyleSheet("")
        self.testButton_2.setObjectName("testButton_2")
        self.settingsUpButton = QtWidgets.QPushButton(self.main_frame)
        self.settingsUpButton.setGeometry(QtCore.QRect(0, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.settingsUpButton.setFont(font)
        self.settingsUpButton.setStyleSheet("background-color:transparent;")
        self.settingsUpButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsUpButton.setIcon(icon)
        self.settingsUpButton.setIconSize(QtCore.QSize(30, 30))
        self.settingsUpButton.setObjectName("settingsUpButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.main_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 701, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.main_frame)
        self.frame.setGeometry(QtCore.QRect(60, 10, 661, 111))
        self.frame.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(36, 172, 242, 0.7);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.testButton = QtWidgets.QPushButton(self.main_frame)
        self.testButton.setGeometry(QtCore.QRect(730, 50, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testButton.setFont(font)
        self.testButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.testButton.setStyleSheet("")
        self.testButton.setObjectName("testButton")
        self.frame.raise_()
        self.settingsUpButton.raise_()
        self.horizontalLayoutWidget.raise_()
        self.testButton.raise_()
        self.testButton_2.raise_()
        self.update_page = QtWidgets.QFrame(self.centralwidget)
        self.update_page.setGeometry(QtCore.QRect(100, 600, 801, 561))
        self.update_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.update_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.update_page.setObjectName("update_page")
        self.updatelistWidget = QtWidgets.QListWidget(self.update_page)
        self.updatelistWidget.setGeometry(QtCore.QRect(420, 90, 271, 421))
        self.updatelistWidget.setObjectName("updatelistWidget")
        self.updateButton = QtWidgets.QPushButton(self.update_page)
        self.updateButton.setGeometry(QtCore.QRect(0, 530, 75, 23))
        self.updateButton.setObjectName("updateButton")
        self.updateDownButton = QtWidgets.QPushButton(self.update_page)
        self.updateDownButton.setGeometry(QtCore.QRect(750, 520, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.updateDownButton.setFont(font)
        self.updateDownButton.setStyleSheet("border-radius:20px;")
        self.updateDownButton.setObjectName("updateDownButton")
        self.label_7 = QtWidgets.QLabel(self.update_page)
        self.label_7.setGeometry(QtCore.QRect(420, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.update_page)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.name_input_4 = QtWidgets.QTextEdit(self.update_page)
        self.name_input_4.setGeometry(QtCore.QRect(10, 70, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.name_input_4.setFont(font)
        self.name_input_4.setObjectName("name_input_4")
        self.updatelistWidget_2 = QtWidgets.QListWidget(self.update_page)
        self.updatelistWidget_2.setGeometry(QtCore.QRect(10, 110, 271, 381))
        self.updatelistWidget_2.setObjectName("updatelistWidget_2")
        self.update_deleteButton = QtWidgets.QPushButton(self.update_page)
        self.update_deleteButton.setGeometry(QtCore.QRect(10, 490, 75, 23))
        self.update_deleteButton.setObjectName("update_deleteButton")
        self.searchbar = QtWidgets.QTextEdit(self.update_page)
        self.searchbar.setGeometry(QtCore.QRect(300, 120, 104, 71))
        self.searchbar.setObjectName("searchbar")
        self.update_backframe = QtWidgets.QFrame(self.centralwidget)
        self.update_backframe.setGeometry(QtCore.QRect(95, 600, 801, 561))
        self.update_backframe.setStyleSheet("border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(48, 168, 196, 0.7), stop:1 rgba(218, 84, 255, 0.7));")
        self.update_backframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.update_backframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.update_backframe.setObjectName("update_backframe")
        self.update_backframe.raise_()
        self.main_frame.raise_()
        self.settings_backframe.raise_()
        self.add_backframe.raise_()
        self.edit_page.raise_()
        self.add_page.raise_()
        self.update_page.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.settingsDownButton.setText(_translate("MainWindow", "🔽"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm"))
        self.addDownButton.setText(_translate("MainWindow", "🔽"))
        self.label_2.setText(_translate("MainWindow", "Select Apps To Add"))
        self.label.setText(_translate("MainWindow", "Type a name for the new button"))
        self.testButton_2.setText(_translate("MainWindow", "<"))
        self.testButton.setText(_translate("MainWindow", ">"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.updateDownButton.setText(_translate("MainWindow", "🔽"))
        self.label_7.setText(_translate("MainWindow", "Select New Apps To Add"))
        self.label_8.setText(_translate("MainWindow", "Change the name "))
        self.update_deleteButton.setText(_translate("MainWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
